// Generated by gencpp from file perception/Coordinates.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_COORDINATES_H
#define PERCEPTION_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception
{
template <class ContainerAllocator>
struct Coordinates_
{
  typedef Coordinates_<ContainerAllocator> Type;

  Coordinates_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , colour(0.0)  {
    }
  Coordinates_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , colour(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _colour_type;
  _colour_type colour;





  typedef boost::shared_ptr< ::perception::Coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinates_

typedef ::perception::Coordinates_<std::allocator<void> > Coordinates;

typedef boost::shared_ptr< ::perception::Coordinates > CoordinatesPtr;
typedef boost::shared_ptr< ::perception::Coordinates const> CoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::Coordinates_<ContainerAllocator1> & lhs, const ::perception::Coordinates_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.colour == rhs.colour;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::Coordinates_<ContainerAllocator1> & lhs, const ::perception::Coordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57cc1fa03d63bd8befee1efa83369c47";
  }

  static const char* value(const ::perception::Coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57cc1fa03d63bd8bULL;
  static const uint64_t static_value2 = 0xefee1efa83369c47ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Coordinates";
  }

  static const char* value(const ::perception::Coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 colour\n"
;
  }

  static const char* value(const ::perception::Coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.colour);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Coordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "colour: ";
    Printer<float>::stream(s, indent + "  ", v.colour);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_COORDINATES_H
