// Generated by gencpp from file perception/deltaHeader.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_DELTAHEADER_H
#define PERCEPTION_MESSAGE_DELTAHEADER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception
{
template <class ContainerAllocator>
struct deltaHeader_
{
  typedef deltaHeader_<ContainerAllocator> Type;

  deltaHeader_()
    : header()
    , delta(0.0)  {
    }
  deltaHeader_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , delta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _delta_type;
  _delta_type delta;





  typedef boost::shared_ptr< ::perception::deltaHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::deltaHeader_<ContainerAllocator> const> ConstPtr;

}; // struct deltaHeader_

typedef ::perception::deltaHeader_<std::allocator<void> > deltaHeader;

typedef boost::shared_ptr< ::perception::deltaHeader > deltaHeaderPtr;
typedef boost::shared_ptr< ::perception::deltaHeader const> deltaHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::deltaHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::deltaHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::deltaHeader_<ContainerAllocator1> & lhs, const ::perception::deltaHeader_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.delta == rhs.delta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::deltaHeader_<ContainerAllocator1> & lhs, const ::perception::deltaHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::deltaHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::deltaHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::deltaHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::deltaHeader_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::deltaHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::deltaHeader_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::deltaHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e858a7275d0626eff6b86b89b98f7d33";
  }

  static const char* value(const ::perception::deltaHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe858a7275d0626efULL;
  static const uint64_t static_value2 = 0xf6b86b89b98f7d33ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::deltaHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/deltaHeader";
  }

  static const char* value(const ::perception::deltaHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::deltaHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 delta\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::perception::deltaHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::deltaHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.delta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct deltaHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::deltaHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::deltaHeader_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "delta: ";
    Printer<float>::stream(s, indent + "  ", v.delta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_DELTAHEADER_H
