// Generated by gencpp from file perception/imu.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_IMU_H
#define PERCEPTION_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception
{
template <class ContainerAllocator>
struct imu_
{
  typedef imu_<ContainerAllocator> Type;

  imu_()
    : yaw(0.0)  {
    }
  imu_(const ContainerAllocator& _alloc)
    : yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::perception::imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::imu_<ContainerAllocator> const> ConstPtr;

}; // struct imu_

typedef ::perception::imu_<std::allocator<void> > imu;

typedef boost::shared_ptr< ::perception::imu > imuPtr;
typedef boost::shared_ptr< ::perception::imu const> imuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::imu_<ContainerAllocator1> & lhs, const ::perception::imu_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::imu_<ContainerAllocator1> & lhs, const ::perception::imu_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2160bf7632f25ad6dc7c5aab561198d4";
  }

  static const char* value(const ::perception::imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2160bf7632f25ad6ULL;
  static const uint64_t static_value2 = 0xdc7c5aab561198d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/imu";
  }

  static const char* value(const ::perception::imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n"
"\n"
;
  }

  static const char* value(const ::perception::imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::imu_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_IMU_H
