// Generated by gencpp from file perception/landmark_points.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_LANDMARK_POINTS_H
#define PERCEPTION_MESSAGE_LANDMARK_POINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception
{
template <class ContainerAllocator>
struct landmark_points_
{
  typedef landmark_points_<ContainerAllocator> Type;

  landmark_points_()
    : land_x()
    , land_y()  {
    }
  landmark_points_(const ContainerAllocator& _alloc)
    : land_x(_alloc)
    , land_y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _land_x_type;
  _land_x_type land_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _land_y_type;
  _land_y_type land_y;





  typedef boost::shared_ptr< ::perception::landmark_points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::landmark_points_<ContainerAllocator> const> ConstPtr;

}; // struct landmark_points_

typedef ::perception::landmark_points_<std::allocator<void> > landmark_points;

typedef boost::shared_ptr< ::perception::landmark_points > landmark_pointsPtr;
typedef boost::shared_ptr< ::perception::landmark_points const> landmark_pointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::landmark_points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::landmark_points_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::landmark_points_<ContainerAllocator1> & lhs, const ::perception::landmark_points_<ContainerAllocator2> & rhs)
{
  return lhs.land_x == rhs.land_x &&
    lhs.land_y == rhs.land_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::landmark_points_<ContainerAllocator1> & lhs, const ::perception::landmark_points_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::landmark_points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::landmark_points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::landmark_points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::landmark_points_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::landmark_points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::landmark_points_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::landmark_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18936a574103be374d81e89f59412a57";
  }

  static const char* value(const ::perception::landmark_points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18936a574103be37ULL;
  static const uint64_t static_value2 = 0x4d81e89f59412a57ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::landmark_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/landmark_points";
  }

  static const char* value(const ::perception::landmark_points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::landmark_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] land_x\n"
"float32[] land_y\n"
;
  }

  static const char* value(const ::perception::landmark_points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::landmark_points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.land_x);
      stream.next(m.land_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct landmark_points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::landmark_points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::landmark_points_<ContainerAllocator>& v)
  {
    s << indent << "land_x[]" << std::endl;
    for (size_t i = 0; i < v.land_x.size(); ++i)
    {
      s << indent << "  land_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.land_x[i]);
    }
    s << indent << "land_y[]" << std::endl;
    for (size_t i = 0; i < v.land_y.size(); ++i)
    {
      s << indent << "  land_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.land_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_LANDMARK_POINTS_H
