// Generated by gencpp from file perception/stateHeader.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_STATEHEADER_H
#define PERCEPTION_MESSAGE_STATEHEADER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace perception
{
template <class ContainerAllocator>
struct stateHeader_
{
  typedef stateHeader_<ContainerAllocator> Type;

  stateHeader_()
    : header()
    , pose()
    , yaw(0.0)  {
    }
  stateHeader_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::perception::stateHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::stateHeader_<ContainerAllocator> const> ConstPtr;

}; // struct stateHeader_

typedef ::perception::stateHeader_<std::allocator<void> > stateHeader;

typedef boost::shared_ptr< ::perception::stateHeader > stateHeaderPtr;
typedef boost::shared_ptr< ::perception::stateHeader const> stateHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::stateHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::stateHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::stateHeader_<ContainerAllocator1> & lhs, const ::perception::stateHeader_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::stateHeader_<ContainerAllocator1> & lhs, const ::perception::stateHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::stateHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::stateHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::stateHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::stateHeader_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::stateHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::stateHeader_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::stateHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a0acb22fe587366fb01abb502b01455";
  }

  static const char* value(const ::perception::stateHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a0acb22fe587366ULL;
  static const uint64_t static_value2 = 0xfb01abb502b01455ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::stateHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/stateHeader";
  }

  static const char* value(const ::perception::stateHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::stateHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point pose\n"
"float32 yaw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::perception::stateHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::stateHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stateHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::stateHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::stateHeader_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_STATEHEADER_H
